### ISSUE TITLE
Group utility functions

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#114]
Need some easy way of getting all the points in a group and related functions.  To start, maybe these:

- flood do (for each stone in group, perform some callback)
- flood fill
- get group
- get border (inner, outer)

Requirements:
 - reasonably efficient
 - Should operate on `Grid` in a generic way.  Maybe a "Fillable" or "GraphLike" interface:
 
```
interface Fillable<IndexT, ValueT> {
    neighbors: (idx: IndexT) => IndexT[];
    at: (idx: IndexT) => ValueT;
    set: (idx: IndexT, value: ValueT) => ValueT;
       ...
}
```

I think #90 has something along these lines, but I haven't looked closely yet.

**Comment by JonKo314** [comment]
Yes, PR #90 will have stuff like that, if it gets completed one day.
