### ISSUE TITLE
badukWithAbstractBoard: passes don't seem to end the game

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#138]
After passing twice, I'd expect to see **Result: B+11.5** or something to that effect. But there is no graphical indication that the game is over.

https://github.com/govariantsteam/govariants/assets/25233703/34479be9-68fd-4ba0-aa0e-6f966893836a

**Comment by merowin** [comment]
This was done with the recent graph board changes. BadukWithAbstractBoard (which is now a legacy variant) uses the same code as Baduk with the corresponding graph board. Passes should also end the game now, so I'm closing this as done.
