### ISSUE TITLE
Create Variants Without Having to Install MongoDB

### ISSUE THREAD

**Issue by JonKo314** [govariantsteam/govariants#150]
It would be nice to make it as easy as possible for new developers to jump into creating new variants. Having to install MongoDB first is a minor inconvenience and a persistent database is not really necessary for variant development and testing.

**Comment by benjaminpjones** [comment]
Good idea!

As a side note, I tried to install mongo on fedora a little while back and it was dang near impossible :/ I don't think that's an issue for any of us, but I guess anecdotally supports that we would benefit an escape hatch.

**Comment by benjaminpjones** [comment]
This may be resolved by #249 

You can test it out by killing the mongo server, and visiting /variants/baduk/demo
