### ISSUE TITLE
[devex] CORS errors in socket io stuff

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#156]
Vite changed the default port from 3000 to 5173 (https://github.com/vitejs/vite/pull/8148).  I believe this is the source of the CORS errors we see in `yarn start`, since our origin is still set to `http://localhost:3000` ([source code](https://github.com/govariantsteam/govariants/blob/40a7258a5a6eb8ddd6ea2de1d0b9a90c64aa4282/packages/server/src/index.ts#L22))

We can either update the origin or pass `--port 3000` to vite.

**Comment by merowin** [comment]
I've tried around a bit, and the following has worked for me:

const LOCAL_ORIGIN = "http://127.0.0.1:5173";

curiously this did not work for me:

const LOCAL_ORIGIN = "http://localhost:5173";

Is the first a sensible solution, or should I try to make it work with the second?

**Comment by benjaminpjones** [comment]
first is a sensible solution, but it does make me wonder... the second solution doesn't work if you change what you enter in the Browser's URL bar?

**Comment by benjaminpjones** [comment]
I'm also seeing potential ipv6 issues: https://stackoverflow.com/a/25657673/5001502

idk, might pan out, but I don't think it's worth the trouble since you already have a solution.

**Comment by merowin** [comment]
> first is a sensible solution, but it does make me wonder... the second solution doesn't work if you change what you enter in the Browser's URL bar?

Yeah good point, if I change the url to http://localhost:5173/ then the second solution works.

**Comment by merowin** [comment]
I think we could close this then, because I've committed and merged the second solution a while ago.

However, when I start the vue-client, the console gives the link http://127.0.0.1:5173 , which I often use to open in browser. So the first solution would be a little bit easier for me to work with (I don't know if its the same for you).

Is there a downside to switching to the first solution?

**Comment by benjaminpjones** [comment]
Either is works for me since localhost resolves to 127.0.0.1 on my computer, but yeah it sounds like a good idea to pick the one that shows up in the terminal
