### ISSUE TITLE
Browse Game Move by Move

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#167]
### What
I think it would be cool to be able to navigate through a game move by move.
### Motivation
This is particularily helpful to learn how the variants exactly work, e.g. for observers, but also helpful for players in correspondence games, to see what happend since the users last visit (think of a multiplayer game), etc.

**Comment by merowin** [comment]
There are multiple ways to achieve this, here are some thoughts.

- On each Navigation, replay moves from start to the current view.
**Pro:** requires not much coding
**Con:** we compute the same thing over and over again
- Change the method exportState of AbstractGame s.t. we provide a move number as input, and get the state at that point. The exact implementation is done by each variant individually.
**Pro:** simple logic in game view, and the variant can implement this as it fits.
**Con:** Adds code complexity to each variant individually.

Here are some thoughts on how a variant could implement this:
1. Deepcopy the state at each move (again easy but possibly a bit wasteful)
2. For the board, each intersection could hold a list that describes the states (colours) of the intersection throughout the game. This allows for some compression, i.e. we don't need an entry for every move, only for those where the value changes.

Of course, parts of the game state other than the board would also need to take this into account.

**Comment by merowin** [comment]
Another thing to consider is that we replay a game on the server each time a move is played. So additional computations as preparation for this would slow this down (sort of unnecessarily, as we need this only for the game view).
So maybe these ideas are not good, I don't know.

**Comment by benjaminpjones** [comment]
See also #13, I think it might be very similar.

As for the design, I strongly prefer the option where variant implementers don't need to add anything special.  Note, if we worry about re-calculation, we can do the deep copy *outside* the variant.

> For the board, each intersection could hold a list that describes the states (colours) of the intersection throughout the game. This allows for some compression, i.e. we don't need an entry for every move, only for those where the value changes.

In some sense, we can view moves as the diff between board states, right?  That leaves me with the question of how many cycles we would actually be saving by performing diffs on a per-intersection basis.

**Comment by merowin** [comment]
Oh, should I close this then, since its a duplicate? Sorry, I wasn't aware, I just thought about this and wanted to write down some thoughts.

**Comment by benjaminpjones** [comment]
They're a little different, so it's okay to leave open, but I wanted to link them because the solutions may need to address both

**Comment by merowin** [comment]
> As for the design, I strongly prefer the option where variant implementers don't need to add anything special.

Yeah makes sense. Perhaps the option
> * On each Navigation, replay moves from start to the current view.

... is not bad afterall.

Then there is a question about variants with parallel moves. I'm thinking that navigating a step forward / backward should be navigating one round forward / backward, i.e. all moves of one round simultaneously. I believe that for this purpose, the round method that we discussed in [#152](https://github.com/govariantsteam/govariants/pull/152) would be useful (perhaps even needed).

**Comment by benjaminpjones** [comment]
Ohh yeah good point! parallel moves are weird but round() would help.

Hidden move variants (e.g phantom) are weird too. Would round() help here also?

**Comment by merowin** [comment]
Hm I don't think so. Yeah hidden move variants are tricky. For a first prototype I think its ok to implement it in a simple way (where with hidden moves, the user sees no board change). But ideally, I think there should be some indication that a hidden move was played, as well as who played it.

**Comment by benjaminpjones** [comment]
Sounds good to me!
