### ISSUE TITLE
Make login persistent especially on mobile

### ISSUE THREAD

**Issue by pdg137** [govariantsteam/govariants#173]
I've noticed I always get logged out within 1 day on the Brave mobile browser, even when trying to keep a correspondence game open in a tab. So I have to go through a tedious process of logging in and backing up a few pages then reloading to find my game again. I am guessing it's because the site uses the default "session" cookie expiration here:

https://github.com/govariantsteam/govariants/blob/main/packages/server/src/index.ts#L98

And I guess mobile browsers expire "session" cookies at random times. Meanwhile Chrome-based desktop browsers don't expire session cookies by default ever:

https://bugs.chromium.org/p/chromium/issues/detail?id=128513

So it's not like we're getting any extra security from this option.

Can we give the session cookie a definite (and long) lifetime?

**Comment by benjaminpjones** [comment]
Oh huh I didn't realize it worked that way

> Can we give the session cookie a definite (and long) lifetime?

Yeah this sounds like a good idea

**Comment by merowin** [comment]
Would it be sufficient to add the maxAge option with value corresponding to a large duration?

I've seen a checkbox on many sites, where users can choose "Stay logged-in" or not. Might be an idea if there are security concerns.

**Comment by pdg137** [comment]
Seems like a long expiration should be good enough if it's good enough for OGS - from a quick test, looks like maybe it does 180 days, with no checkbox.

**Comment by merowin** [comment]
I would like this as well. @JonKo314 do you object to this? You know more about security etc. than me.

**Comment by JonKo314** [comment]
No objection from me, as this is a pretty common behavior. I think convenience trumps security here, since we're not working on a banking app or something like that.
