### ISSUE TITLE
Some Moves Shouldn’t Be Sent to Clients

### ISSUE THREAD

**Issue by JonKo314** [govariantsteam/govariants#174]
Currently all moves of a game are sent to the clients via the `GET` `/games/:gameId` route. That's a problem in variants with parallel moves, because moves of an ongoing round should be secret.

**Comment by benjaminpjones** [comment]
Agreed! See also https://github.com/govariantsteam/govariants/issues/48

**Comment by merowin** [comment]
I think we generally need a plan for hidden information. For Parallel Variants it seems to be sufficient to remove the staged moves (except yours). For other hidden information games, maybe variants could be capeable of obfuscating moves, or similar.

**Comment by merowin** [comment]
Should we close this?

**Comment by benjaminpjones** [comment]
I think so. The only outstanding "todo" is that we haven't fully hidden the old APIs right?

**Comment by merowin** [comment]
> I think so. The only outstanding "todo" is that we haven't fully hidden the old APIs right?

Yeah, and I guess that there is no server side validation of the socket subscriptions.

**Comment by merowin** [comment]
I made a follow-up issue: https://github.com/govariantsteam/govariants/issues/301 and thus this can be closed.
