### ISSUE TITLE
[layout] too much blank space at top when there are many players

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#180]
I've git bisected, and the culprit is https://github.com/govariantsteam/govariants/commit/86c8da7d79b312f3d9d3cda5e49a06923cf26d42.  I do not yet know the root cause.

To reproduce:

0) open Responsive design tool to test mobile (it is more noticeable there)
1) start a game
    - variant: "parallel"
    - number of players: 20
2) go to the game page
3) observe a lot of empty space on top

## Screenshots

Before 86c8da7d79b312f3d9d3cda5e49a06923cf26d42 (correct)
<img width="314" alt="Screenshot 2024-02-02 at 9 38 09 PM" src="https://github.com/govariantsteam/govariants/assets/25233703/05ba6fe9-3b02-4130-8dba-f4d9b97f9776">

After (incorrect)
<img width="415" alt="Screenshot 2024-02-02 at 9 34 37 PM" src="https://github.com/govariantsteam/govariants/assets/25233703/75e1fe52-ab26-4343-8619-e87f3ccdc343">

**Comment by merowin** [comment]
Good catch! There was a superfluous grid-layout in div id=app introduced in the nav-bar pr, I didn't notice until after merging 😅
