### ISSUE TITLE
Mobile screen sizes: move navigation arrows up next to the board

### ISSUE THREAD

**Issue by pdg137** [govariantsteam/govariants#181]
It would be helpful to have the forward/back arrows up next to the board, above the list of players:

![image](https://github.com/govariantsteam/govariants/assets/466760/50c07963-fbe1-4a5b-a1ad-699c24440aac)

Since otherwise it's hard to navigate while looking at the board. The list of players is much less useful. (Not sure why there's so much extra whitespace when I use mobile mode of the Chrome inspector - it looks a little better on an actual phone.)

**Comment by pdg137** [comment]
Actually this looks like the reason it's weird on desktop Chrome, a `height="100%"` on the SVG tag:

https://github.com/govariantsteam/govariants/blob/main/packages/vue-client/src/components/boards/BadukBoardAbstract.vue#L51

Not sure what that height is supposed to be relative to; it doesn't seem to do anything useful.

**Comment by benjaminpjones** [comment]
I haven't checked, but this might be fixed by #179
