### ISSUE TITLE
[FR] Clock

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#19]
I'm not really sure how this should work, but time settings are a pretty big part of the game.

**Comment by merowin** [comment]
I was not aware that linking the pull requests would automatically close this issue on merge. There are still things that I'd like to do here:

implement further time control types (Fischer etc.)
improve the code health (maybe add some abstraction to make adding new control types easier)
add new variants to the time handler map
improve the game clock UI (I'm thinking maybe just display the top-two non-zero units among [day, hour, minute, second])

**Comment by merowin** [comment]
Closing this, as I believe I reached a relatively good basis, and future time controls should get new issues.
