### ISSUE TITLE
Quantum Go

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#198]
Rules (as I understood):

Played on two (entangled) boards, every move places a stone on both boards at the same position. The move must be a legal move on both boards (with respect to normal go rules). Every stone is entangled with its counterpart on the other board, in the sense that a capture on one board implies the other entangled stone also being captured.

The first two moves are special (quantum-) moves: the black and white stone switch places on one of the boards (i.e. if black plays d3 and white e3, one board will have swapped stones: black on e3, white on d3). The two black stones (respectively white) are also entangled in the same sense as above (and specially marked).

At the end of the game, the resulting score is the average of both boards.

Alternatively: Before the first move both players secretly chooses one of the boards. If both chose the same board, only its score is taken. Otherwise the average score, as above.

**Comment by benjaminpjones** [comment]
Oh I forgot that removing stones could remove stones on the other board. That complicates things a bit.  Well need some way of modifying the board state in a way that's not consistent with standard go rules.

Additionally, does this "quantum capture" apply to non-quantum stones? I thought only the green stones were entangled

**Comment by benjaminpjones** [comment]
I went ahead and created a branch for this variant!  I haven't implemented any game logic, but wanted to get the mappings and graphical interface set up since that is the part that is probably more complicated for a newcomer to our codebase.

**Comment by benjaminpjones** [comment]
Had a chance to run the program this weekend, and I think you're right that "normal" stones are also entangled.  All stones are connected to another stone on the other board, although the "quantum" stones are connected to a different coordinate (remove one white stone, and the white stone is removed on the other board)

https://github.com/govariantsteam/govariants/assets/25233703/615a59d5-30e9-49f8-b9b7-5c1ce8ac95b4

https://github.com/govariantsteam/govariants/assets/25233703/3d362a0a-c432-4519-894a-d04c137413ad

**Comment by benjaminpjones** [comment]
Linking #202 (main implementation) and follow-ups #217 #218 #220.  I believe this is implemented! We can address bugs or enhancements in new issues.
