### ISSUE TITLE
[Thue-Morse] Refinements

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#200]
Couple of ideas:

1.) Remove the check for (Super-) Ko, because the non-periodical move order rules out all cycles already
2.) Add visual indicator for the next moves that are coming up (e.g. display the next 6 or so move colors) <- this could also be scrollable

An idea (+ request) from a Thue-Morse Go enthusiast: Display the current move number in binary / hexadecimal / base 8

**Comment by benjaminpjones** [comment]
+1 to both ideas

For (2), https://github.com/govariantsteam/govariants/issues/134 might help
