### ISSUE TITLE
hash password before login request

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#210]
From the network tab, it looks like the users password is sent in plaintext in the login request.

I believe this is not ideal from a security standpoint, especially since some people may reuse a password on multiple websites.

So I think the password should be hashed somehow before the client sends the http request.

**Comment by benjaminpjones** [comment]
We can't rely on the network encryption of HTTPS? What scenario would we be protecting against?

**Comment by merowin** [comment]
Hm I guess you are right, sorry.

**Comment by JonKo314** [comment]
Never wrong to look twice at (password) security. But yeah, HTTPS should be sufficient for communicating the password.
