### ISSUE TITLE
Display player colors or symbols

### ISSUE THREAD

**Issue by evizam** [govariantsteam/govariants#211]
Currently, it's hard to tell for an observer of a game which player is playing which color. For some variants (e.g. fractional go) it's even impossible.

My proposal is to add an indicator to each player seat. For example, a stone in the player's color next to the player number. To keep this "abstract", every game variant could define a "symbol" for each player (and each round, in case that can change) and pass it to the player seat.

**Comment by merowin** [comment]
Since we've got a prototype that works for all current variants relatively well, I'll close this for now.
