### ISSUE TITLE
Overlapping Layout in game page for variant quantum

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#257]
In the game page for variant quantum, the next-to-play-indicator overlaps the navigation buttons:

![grafik](https://github.com/govariantsteam/govariants/assets/77507448/e47ef751-ea87-426c-bafc-6972e85fbf71)

This is not the case for other variants:

![grafik](https://github.com/govariantsteam/govariants/assets/77507448/ee77161c-5165-4c53-805d-c311703e6e0e)

**Comment by benjaminpjones** [comment]
What's the browser configuration and display size? I haven't seen this myself:

![Screenshot_20240511_080433_Firefox](https://github.com/govariantsteam/govariants/assets/25233703/02e6d5c5-e07f-444e-a266-538e25bd76dd)

Browser: Firefox (Android)
Screen size: 360x780

**Comment by merowin** [comment]
Browser: Firefox
Screen size: 1920 x 1080

**Comment by merowin** [comment]
Correction: This is not only the case for quantum go. It seems that it depends on the board component. For example, the new graph board component also has this issue on this screen size:
![grafik](https://github.com/govariantsteam/govariants/assets/77507448/923981bb-d0e0-4890-a51b-a061f64d7254)
