### ISSUE TITLE
Optimize network calls wrt. game-state handling in the game view

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#269]
See this conversation:

> If we want to nit pick on efficiency, there are also a few low-hanging network issues I think we could also leave as follow-up tasks:
> 
> - Two state requests are sent on page load.
> 
> <img width="797" alt="Screenshot 2024-06-09 at 6 05 38 PM" src="https://github.com/govariantsteam/govariants/assets/25233703/11202871-9413-4971-b49c-91c08ae708eb">
> 
> - Taking a seat sends N "unsubscribe" messages, we should only need to send 1.
> 
> <img width="551" alt="Screenshot 2024-06-09 at 6 05 18 PM" src="https://github.com/govariantsteam/govariants/assets/25233703/9a081437-fcb5-48f5-8ba4-927b3445f323">
> 
> - Two state messages are sent from the server when game state changes (I believe this is because the client subscribes to both the observer state and seat-specific state.
> 
> <img width="524" alt="Screenshot 2024-06-09 at 6 05 12 PM" src="https://github.com/govariantsteam/govariants/assets/25233703/1ffd4335-c9ed-4974-a83d-778f82071f7d">
> 
> _Originally posted by @benjaminpjones in https://github.com/govariantsteam/govariants/issues/267#issuecomment-2156818609_

**Comment by merowin** [comment]
This is probably fixed with https://github.com/govariantsteam/govariants/pull/297

**Comment by benjaminpjones** [comment]
Oh yeah! The second two are definitely resolved. Is the first?

> Two state requests are sent on page load.

**Comment by merowin** [comment]
Oh right, the first is not resolved yet. The endpoint `/games/:gameId/state/initial` returns the variant and config, which are not included in endpoint `/games/:gameId/state`. I haven't checked this, but I believe this structure may have incidentally fixed #266 So I would like to keep it.

But maybe we can avoid that both api calls get triggered at the start.

**Comment by benjaminpjones** [comment]
That's a good point! And tbh two REST calls at page load is not such a big deal. Let's go ahead and close both of these, and can revisit later if API calls become an issue.
