### ISSUE TITLE
[dev] npm start doesn't seem to update shared

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#28]
I'm not sure how to fix this.  Maybe by importing the ts files into client/server directly rather than pointing to the dist dir.

**Comment by merowin** [comment]
Would it be possible to add a script that first builds shared, and then builds + starts the server / vue-client?

**Comment by JonKo314** [comment]
I think there should be some yarn setup that just makes this work with workspaces, but I haven't figured out how to do it yet.

**Comment by benjaminpjones** [comment]
We are already using `-t`/`--topological` flag in the build script (see [workspaces foreach](https://yarnpkg.com/cli/workspaces/foreach) docs), which (I think) ensures `shared:build` gets called first.  It would be straightforward to roll `build` into the `start` command.

```
"start": "yarn build && yarn workspaces foreach -pi run start",
```

**However**, I don't think that would be sufficient to resolve this issue, since we want both servers to update on code changes in `shared`.  I think we might need something additional config for the watcher commands (`nodemon` for server, `vite` for vue-client).  And maybe some way to bypass the build command in shared, and let `vue-client` and `server` compile the `shared` TS.

**Comment by benjaminpjones** [comment]
https://github.com/vitejs/vite/issues/819

For the Vite side, I think there is a solution in this thread
