### ISSUE TITLE
Quantum Games seem to be broken

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#286]
When I open the game view of a game of quantum go, I get "Error: Cannot read properties of undefined (reading 'badukGame')"

**Comment by bpjatfb** [comment]
This should be fixed by #285 (deployed this morning) are you still noticing it?

**Comment by benjaminpjones** [comment]
Thus should be fixed by #285 (deployed this morning). Are you still seeing it?

**Comment by merowin** [comment]
Right, thanks!
