### ISSUE TITLE
Quantum Go Game Engine

### ISSUE THREAD

**Issue by SameerDalal** [govariantsteam/govariants#287]
Hi Everyone,

Over the past month, I've been developing a game engine for Quantum Go! You can check it out here: [`github.com/SameerDalal/QuantumGo_Engine`](https://github.com/SameerDalal/QuantumGo_Engine).

I built this engine entirely from scratch without using any machine learning libraries. Currently, the engine uses the Monte Carlo Tree Search Algorithm to determine the best moves. I'm also working on a reinforcement learning model using TensorFlow for a more powerful QuantumGo engine.

For a simple setup, use the `main` branch. However, if you want to play multiple games with the engine, I recommend the GPU-accelerated version available in the `cuda` branch.

All the setup instructions are in the repository documentation, but let me know if you have any questions. I'd love to hear what you think!

**Comment by benjaminpjones** [comment]
Very cool! I noticed there were some bot games popping up :)

Would you be open to adding an open source LICENSE to your repo? Otherwise it's not advisable to browse/modify the source.

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by SameerDalal** [comment]
Thank you, I just added it!

**Comment by benjaminpjones** [comment]
I took a look tonight, and played around with it - noticed there may actually be an opportunity for a significant speedup in the CPU version (see https://github.com/SameerDalal/QuantumGo_Engine/pull/3).  It's a cool project, thanks for sharing your work!

**Comment by benjaminpjones** [comment]
Closing since no action item. Thanks again for sharing!
