### ISSUE TITLE
Green colour does not get captured

### ISSUE THREAD

**Issue by merowin** [govariantsteam/govariants#358]
In this game, when the white quantum stone gets captured, the green colour (quantum placement) does not get removed.

![grafik](https://github.com/user-attachments/assets/b3582a4b-c604-47ec-a180-771ea0af6eaa)
->
![grafik](https://github.com/user-attachments/assets/319baf82-0c92-44a0-8636-ba8fdcc65f3e)

https://www.govariants.com/game/67527888998b9ba55f180008

**Comment by benjaminpjones** [comment]
Guessing this was introduced by #328 as it looks like a display issue
