### ISSUE TITLE
[CI] run tsc on PRs and pushes to main

### ISSUE THREAD

**Issue by benjaminpjones** [govariantsteam/govariants#97]
The launch command runs `tsc` on `server`, so we want to make sure it passes.  Also it's good to check the types anyway.

Somewhat related - maybe we don't want heroku checking types?  I believe transpilers such as babel can convert to JS faster and they won't die because of missing types..

**Comment by JonKo314** [comment]
As long as it isn't too tedious, I'd rather be more strict regarding type checking. So I think Heroku failing is okay.

**Comment by benjaminpjones** [comment]
On the whole, I'm on board with making our type checking more strict!

The question here though isn't really "how strict do we want it?" but "where do we want to check for it?".  I think it's better to see these errors on GitHub (CI) than in Heroku (where we might not see it until someone checks the website)

**Comment by JonKo314** [comment]
Yeah, sorry, I should have been more clear: I agree that running `tsc` on PRs is very useful, but I don't really know about using transpilers. For now I think I'd rather have a dead server, than a running one with hidden bugs due to missing type checks.

**Comment by benjaminpjones** [comment]
This is actually resolved - "build" already runs as part of the [PR workflow](https://github.com/govariantsteam/govariants/blob/16a6bb1c36e5cb8c35c05d6c51fc328481175047/.github/workflows/node.js.yml#L30), and #243 added `tsc` to the "build" script.
